name: comfy_memo
description: "An app that improves memorization through interval repetition"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  meta: any
  
  freezed_annotation: ^2.4.4

  dynamic_color: ^1.7.0

dev_dependencies:
  freezed: ^2.5.7

  build_runner: ^2.4.14


flutter:
  uses-material-design: true
