name: comfy_memo
description: "An app that improves memorization through interval repetition"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  meta: any
  mockito: ^5.4.4

  dynamic_color: ^1.7.0

dev_dependencies:
  test: ^1.25.7
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
